name: CI - Aquala

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Verificar estructura del proyecto
        run: |
          echo "✅ Pipeline ejecutado correctamente"
          echo "📁 Archivos del proyecto:"
          ls -la